apps/php5/5.4.45/conf/php.ini
apps/php5/5.5.38/conf/php.ini
apps/php5/5.6.40/conf/php.ini
apps/php7/7.0.33/conf/php.ini
apps/php7/7.1.33/conf/php.ini
apps/php7/7.2.34/conf/php.ini
apps/php7/7.3.33/conf/php.ini
apps/php7/7.4.33/conf/php.ini
apps/php8/8.0.28/conf/php.ini
apps/php8/8.1.18/conf/php.ini
apps/php8/8.2.5/conf/php.ini

Refs https://github.com/1Panel-dev/1Panel/issues/1410

fix: 解决禁用函数导致的 gd 安装失败 和 composer 无法使用的问题

---

apps/rustdesk/s6-latest/data.yml
apps/rustdesk/s6-latest/docker-compose.yml

```
feat:添加只需运行一个容器版本的rustdesk(s6)
```

feat:添加只需运行一个容器版本的rustdesk(s6)

---

apps/emqx/5.1.6/data.yml
apps/emqx/5.1.6/docker-compose.yml

fix emqx error

---

apps/phpmyadmin/5.2.1/conf.inc/config.user.inc.php

phpMyAdmin 隐藏数据库 `information_schema|performance_schema`

phpMyAdmin 隐藏数据库 `information_schema|performance_schema`

---

apps/palworld/0.12.0/data.yml
apps/palworld/0.12.0/docker-compose.yml

feat:添加在线安装版本的palworld-server

---

apps/umami/2.9.0/docker-compose.yml

解决 https://github.com/1Panel-dev/1Panel/issues/4002
https://github.com/umami-software/umami/blob/master/docker-compose.yml#L11

modify var name

---

apps/mblog/README.md

Update mblog README.md

---

apps/php7/7.0.33/build/php/Dockerfile
apps/php7/7.1.33/build/php/Dockerfile
apps/php7/7.2.34/build/php/Dockerfile
apps/php7/7.3.33/build/php/Dockerfile
apps/php7/7.4.33/build/php/Dockerfile

edit php7 Dockerfile, fix timezone command

---

apps/frpc/0.56.0/data.yml
apps/frpc/0.56.0/data/frpc.toml
apps/frpc/0.56.0/data/frpc_full.toml
apps/frpc/0.56.0/docker-compose.yml
apps/frps/0.56.0/data.yml
apps/frps/0.56.0/data/frps.toml
apps/frps/0.56.0/data/frps_full.toml
apps/frps/0.56.0/docker-compose.yml

feat:修正并添加frp的tls设置

---

apps/jumpserver/3.10.7/docker-compose.yml

fix: 修正 JumpServer 持久化路径

---

apps/php5/5.4.45/build/config.json
apps/php5/5.5.38/build/config.json
apps/php5/5.6.40/build/config.json
apps/php7/7.0.33/build/config.json
apps/php7/7.0.33/build/php/extensions/install.sh
apps/php7/7.1.33/build/config.json
apps/php7/7.1.33/build/php/extensions/install.sh
apps/php7/7.2.34/build/config.json
apps/php7/7.2.34/build/php/extensions/install.sh
apps/php7/7.3.33/build/config.json
apps/php7/7.3.33/build/php/extensions/install.sh
apps/php7/7.4.33/build/config.json
apps/php7/7.4.33/build/php/extensions/install.sh
apps/php8/8.0.30/build/config.json
apps/php8/8.0.30/build/php/extensions/install.sh
apps/php8/8.1.27/build/config.json
apps/php8/8.1.27/build/php/extensions/install.sh
apps/php8/8.2.15/build/config.json
apps/php8/8.2.15/build/php/extensions/install.sh

Refs https://github.com/1Panel-dev/1Panel/issues/4871

fix: 解决 ssh2 安装失败的问题

---

apps/mssql/2017-latest/data.yml
apps/mssql/2017-latest/docker-compose.yml
apps/mssql/2017-latest/scripts/init.sh
apps/mssql/2019-latest/data.yml
apps/mssql/2019-latest/docker-compose.yml
apps/mssql/2019-latest/scripts/init.sh

'mssql2017-2019'

---

apps/node/12.22.12/docker-compose.yml
apps/node/14.21.3/docker-compose.yml
apps/node/16.20.2/docker-compose.yml

Refs https://github.com/1Panel-dev/1Panel/issues/5813

feat: 修改 Node 12 14 16 版本镜像地址

---

apps/go/1.21/run.sh
apps/go/1.22/run.sh
apps/java/1.8/run.sh
apps/java/11/run.sh
apps/java/17/run.sh
apps/java/21/run.sh
apps/java/22/run.sh

Refs https://github.com/1Panel-dev/1Panel/issues/6079

fix: 运行环境启动脚本包含引号时报错

---

apps/openresty/1.21.4.3-3-3-focal/docker-compose.yml

Refs https://github.com/1Panel-dev/1Panel/issues/6073

fix: Openresty 未挂载 mime.types

---

apps/php7/7.0.33/build/php/extensions/install.sh
apps/php7/7.1.33/build/php/extensions/install.sh
apps/php7/7.2.34/build/php/extensions/install.sh
apps/php7/7.3.33/build/php/extensions/install.sh
apps/php7/7.4.33/build/php/extensions/install.sh
apps/php8/8.0.30/build/php/extensions/install.sh
apps/php8/8.1.29/build/php/extensions/install.sh
apps/php8/8.2.20/build/php/extensions/install.sh
apps/php8/8.3.8/build/php/extensions/install.sh

Refs https://github.com/1Panel-dev/1Panel/issues/6351

fix: 解决 PHP 无法安装 Snuffleupagus 的问题

---

apps/php7/7.0.33/build/php/extensions/install.sh
apps/php7/7.1.33/build/php/extensions/install.sh
apps/php7/7.2.34/build/php/extensions/install.sh
apps/php7/7.3.33/build/php/extensions/install.sh
apps/php7/7.4.33/build/php/extensions/install.sh
apps/php8/8.0.30/build/php/extensions/install.sh
apps/php8/8.1.29/build/php/extensions/install.sh
apps/php8/8.2.20/build/php/extensions/install.sh
apps/php8/8.3.8/build/php/extensions/install.sh

Refs https://github.com/1Panel-dev/1Panel/issues/6535

fix: 解决 PHP 环境安装 pdo_oci 失败的问题

---

apps/php7/7.0.33/build/php/extensions/install.sh
apps/php7/7.1.33/build/php/extensions/install.sh
apps/php7/7.2.34/build/php/extensions/install.sh
apps/php7/7.3.33/build/php/extensions/install.sh
apps/php7/7.4.33/build/php/extensions/install.sh
apps/php8/8.0.30/build/php/extensions/install.sh
apps/php8/8.1.29/build/php/extensions/install.sh
apps/php8/8.2.20/build/php/extensions/install.sh
apps/php8/8.3.8/build/php/extensions/install.sh

Refs https://github.com/1Panel-dev/1Panel/issues/6549

fix: 解决 PHP 安装  oci8 扩展失败问题

---

apps/affine/stable/docker-compose.yml

Update affine docker-compose.yml

---

apps/halo/2.20.10/data.yml

This PR refines English translation of Halo form fields.
```release-note
None
```

Refine English translation of Halo form fields

---

apps/openresty/README_en.md

This PR adds English README for OpenResty app, mainly using Copilot.
```release-note
None
```

Add English README for OpenResty app

---

apps/mysql/README_en.md

This PR adds English README for MySQL app, mainly using Copilot.
```release-note
None
```

Add English README for MySQL app

---

apps/redis/README_en.md

This PR adds English README for Redis app, mainly using Copilot.
```release-note
None
```

Add English README for Redis app

---

apps/alist/README.md
apps/alist/README_en.md

This PR adds English README for AList app.
```release-note
None
```

Add English README for AList app

---

apps/wordpress/README_en.md

This PR adds English README for Wordpress app, mainly using Copilot.
```release-note
None
```

Add English README for Wordpress app

---

apps/postgresql/README_en.md

This PR adds English README for PostgreSQL app.

docs: Add English README for PostgreSQL app

---

apps/gitea/README_en.md

This PR adds English README for Gitea app.

docs: Add English README for Gitea app

---

apps/mariadb/README_en.md

This PR adds English README for MariaDB app.

docs: Add English README for MariaDB app

---

apps/ollama/README_en.md

This PR adds English README for Ollama app.

docs: Add English README for Ollama app

---

apps/minio/README_en.md

This PR adds English README for MinIO app.

docs: Add English README for MinIO app

---

apps/rustdesk/README_en.md

This PR adds English README for RustDesk app.

docs: Add English README for RustDesk app

---

apps/act_runner/README_en.md

This PR adds English README for Act Runner app.

docs: Add English README for Act Runner app

---

apps/bitwarden/README_en.md

This PR adds English README for Bitwarden app.

docs: Add English README for Bitwarden app

---

apps/it-tools/README.md
apps/it-tools/README_en.md

This PR adds English README for it-tools app.

docs: Add English README for it tools app

---

apps/nginx-proxy-manager/README_en.md

This PR adds English README for nginx proxy app.

docs: Add English README for Nginx Proxy app

---

apps/phpmyadmin/README_en.md

This PR adds English README for phpMyAdmin app.

docs: Add English README for phpMyAdmin app

---

apps/php5/README_en.md
apps/php7/README_en.md
apps/php8/README_en.md

This PR adds English README for php app.

docs: Add English README for php app

---

apps/maddy-mail/README_en.md
apps/mailserver/README_en.md
apps/metabase/README_en.md
apps/palworld-server-tool/README_en.md
apps/palworld/README_en.md
apps/roundcube/README_en.md
apps/uptime-kuma/README_en.md

docs: Add English README 

---

apps/nocobase/1.6.23/docker-compose.yml

feat: Add DB_PORT parameter to Nocobase

---

apps/casdoor/1.957.0/scripts/upgrade.sh

🐛 fixed(casdoor): add upgrade script

---

apps/alist/3.45.0/data.yml
apps/alist/3.45.0/docker-compose.yml

🐛 fix(alist): modify the s3 port to be correct

---

apps/openresty/1.27.1.2-2-2-focal/1pwaf/data/rules/app/Halo.json

Refs https://github.com/1Panel-dev/1Panel/issues/9934

feat: Update Halo rule for waf 

---

apps/php/5/build/data/install-ext
apps/php/7/build/data/install-ext

https://github.com/1Panel-dev/1Panel/issues/8975

feat: change php install-ext script

---

apps/mysql/8.4.6/conf/my.cnf

https://github.com/1Panel-dev/1Panel/issues/10088

chore(mysql): update default my.cnf for v8.4
